### ISSUE TITLE
Issue 1

### ISSUE THREAD

**Issue by chelobotix** [haftamudesta/LeaderBoard#2]
Good work Haftamu. Very nice work with UI.
- [ ] I suggest you think about changing the name of your fucntio from Rebner to Render to make it clearer.
https://github.com/haftamudesta/LeaderBoard/blob/4f1e6a9a0751e0694ce21e10ad274ebe5df5eeb4/module/addItem.js#L32

**Comment by haftamudesta** [comment]
issue solved
